#!/usr/bin/env bash

PYTHON_PACKAGE=$1

if [ -z "$PYTHON_PACKAGE" ]; then
    echo "Name of Python package"
    exit 1
fi

BLOB_PREFIX="$PYTHON_PACKAGE/vendor"
TMP_DIR=$(mktemp -d)
WHEELS_LOCAL_DESTINATION="$TMP_DIR/$BLOB_PREFIX"

mkdir -p "${TMP_DIR}/${BLOB_PREFIX}"

# Download wheel files for Python package
pip wheel "$PYTHON_PACKAGE" -w "$WHEELS_LOCAL_DESTINATION"

while IFS= read -r -d '' filename
do
  echo "file: $filename"
  blob_name=${filename/$TMP_DIR\//}
  echo "blob name: $blob_name"
  bosh add-blob "$filename" "$blob_name"
done < <(find "$WHEELS_LOCAL_DESTINATION" -name '*.whl' -print0)

rm -rf "$TMP_DIR"
